import { Container } from "react-bootstrap";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
